import { test, expect, type Page } from '@playwright/test'

test.use({ baseURL: process.env.WORDMERGE_GAME_URL ?? 'http://127.0.0.1:5178' })

test('rapid mouse clicks with small drift retain following, but crossing the drag threshold pans without clicking', async ({ page }) => {
  await enter(page)
  await page.clock.install()
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 50))
  const scene = page.getByTestId('camp-scene'), game = page.getByTestId('survival-game')
  await tapPoint(page, 10, 10)
  await page.clock.runFor(100)
  for (const drift of [12, 18, 10]) {
    const [cx, cy, zoom] = (await scene.getAttribute('data-camera'))!.split(',').map(Number)
    const bounds = (await page.getByTestId('camp-canvas').boundingBox())!
    const x = bounds.x + cx, y = bounds.y + cy + 20 * 16 * zoom
    await page.mouse.move(x, y); await page.mouse.down()
    await page.mouse.move(x + drift, y, { steps: 3 }); await page.mouse.up()
    await page.clock.runFor(100)
    await expect(scene).toHaveAttribute('data-camera-follow', 'player')
    const expectedX = Number((10 + drift / (64 * zoom)).toFixed(4))
    const expectedY = Number((10 - drift / (64 * zoom)).toFixed(4))
    const [actualX, actualY] = (await game.getAttribute('data-destination'))!.split(',').map(Number)
    expect(actualX).toBeCloseTo(expectedX, 3); expect(actualY).toBeCloseTo(expectedY, 3)
  }
  const destination = await game.getAttribute('data-destination')
  await page.mouse.move(170, 380); await page.mouse.down()
  await page.mouse.move(190, 380, { steps: 4 }); await page.clock.runFor(50)
  await expect(scene).toHaveAttribute('data-camera-follow', '')
  const panned = await scene.getAttribute('data-camera')
  await page.clock.runFor(100)
  expect(await scene.getAttribute('data-camera')).toBe(panned)
  // Once dragging, returning inside the threshold must not turn release into a click.
  await page.mouse.move(171, 380); await page.mouse.up(); await page.clock.runFor(50)
  expect(await game.getAttribute('data-destination')).toBe(destination)
  await expect(scene).toHaveAttribute('data-camera-follow', '')
})

async function enter(page: Page) {
  await page.goto('/?game=survival')
  await expect(page.getByTestId('camp-scene')).toHaveAttribute('data-ready', 'true')
  await expect(page.getByTestId('survival-game')).toHaveAttribute('data-save-state', 'saved')
}
async function tapPoint(page: Page, x: number, y: number) {
  const camera = (await page.getByTestId('camp-scene').getAttribute('data-camera'))!.split(',').map(Number)
  const bounds = (await page.getByTestId('camp-canvas').boundingBox())!
  await page.touchscreen.tap(bounds.x + camera[0] + (x - y) * 32 * camera[2], bounds.y + camera[1] + (x + y) * 16 * camera[2])
}
async function position(page: Page) {
  const [x, y] = (await page.getByTestId('camp-scene').getAttribute('data-position'))!.split(',').map(Number)
  return { x, y }
}

test('a water tap replaces an ongoing walk and reaches the water destination after reload', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await enter(page)
  await page.clock.install()
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 50))
  await tapPoint(page, 9.3, 10.3)
  await page.clock.runFor(150)
  await tapPoint(page, 4, 3)
  await page.clock.runFor(100)
  await expect(page.getByTestId('survival-game')).toHaveAttribute('data-destination', '4,3')
  await page.evaluate(() => window.dispatchEvent(new PageTransitionEvent('pagehide')))
  await page.clock.runFor(50)
  await expect(page.getByTestId('survival-game')).toHaveAttribute('data-save-state', 'saved')
  await page.reload()
  await expect(page.getByTestId('camp-scene')).toHaveAttribute('data-ready', 'true')
  await page.clock.runFor(6000)
  expect(await position(page)).toEqual({ x: 4, y: 3 })
  await expect(page.getByTestId('survival-game')).toHaveAttribute('data-activity', 'idle')
  await tapPoint(page, 4, 3)
  await page.clock.runFor(500)
  expect(await position(page)).toEqual({ x: 4, y: 3 })
  expect(errors).toEqual([])
})

test('camera follows walking, manual drag suspends it, locating and walking resume it', async ({ page }) => {
  await enter(page)
  await page.clock.install()
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 50))
  const scene = page.getByTestId('camp-scene')
  const offset = async () => scene.evaluate(element => {
      const host = element as HTMLElement, [cx, cy, zoom] = host.dataset.camera!.split(',').map(Number)
      const [x, y] = host.dataset.position!.split(',').map(Number)
      return Math.hypot(cx + (x - y) * 32 * zoom - host.clientWidth / 2,
        cy + (x + y) * 16 * zoom - host.clientHeight / 2)
    })
  const centered = async () => { expect(await offset()).toBeLessThan(.1) }
  const pan = async () => {
    await page.mouse.move(170, 380); await page.mouse.down()
    await page.mouse.move(220, 410, { steps: 5 }); await page.mouse.up()
    await page.clock.runFor(50)
    await expect(scene).toHaveAttribute('data-camera-follow', '')
    const camera = await scene.getAttribute('data-camera'), before = await position(page)
    await page.clock.runFor(150)
    expect(await scene.getAttribute('data-camera')).toBe(camera)
    expect(await position(page)).not.toEqual(before)
  }
  await tapPoint(page, 10, 10)
  await page.clock.runFor(200)
  await centered()
  const following = await scene.getAttribute('data-camera')
  await page.clock.runFor(100)
  expect(await scene.getAttribute('data-camera')).not.toBe(following)
  await centered()
  await pan()
  await page.getByRole('button', { name: '定位主角' }).click()
  await page.clock.runFor(50)
  await expect(scene).toHaveAttribute('data-camera-follow', 'player')
  expect(await offset()).toBeGreaterThan(1)
  expect(await offset()).toBeLessThan(60)
  await pan()
  await tapPoint(page, 9.25, 10.2)
  await page.clock.runFor(100)
  await expect(scene).toHaveAttribute('data-camera-follow', 'player')
  expect(await offset()).toBeGreaterThan(1)
  await page.clock.runFor(1500)
  expect(await position(page)).toEqual({ x: 9.25, y: 10.2 })
  await centered()
})

test('a touch drag wins over a pending walk and stays where the player leaves it', async ({ page, context }) => {
  await enter(page)
  await page.clock.install()
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 50))
  const scene = page.getByTestId('camp-scene'), cdp = await context.newCDPSession(page)
  // Drag before the queued walk has reached its first simulation step.
  await tapPoint(page, 10, 10)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ id: 1, x: 160, y: 380 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ id: 1, x: 230, y: 420 }] })
  await page.clock.runFor(16)
  const dragged = await scene.getAttribute('data-camera')
  await page.clock.runFor(300)
  await expect(scene).toHaveAttribute('data-camera-follow', '')
  expect(await scene.getAttribute('data-camera')).toBe(dragged)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await page.clock.runFor(300)
  expect(await scene.getAttribute('data-camera')).toBe(dragged)
  expect((await position(page)).x).toBeGreaterThan(7)
  await tapPoint(page, 9.25, 10.2)
  await page.clock.runFor(100)
  await expect(scene).toHaveAttribute('data-camera-follow', 'player')
})

test('touch movement reaches the exact point inside a cell, pauses and reloads at the same position', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await enter(page)
  await tapPoint(page, 9.25, 10.2)
  await expect(page.getByTestId('survival-game')).toHaveAttribute('data-destination', '9.25,10.2')
  await expect(page.getByTestId('survival-game')).toHaveAttribute('data-activity', 'idle')
  await expect.poll(() => position(page)).toEqual({ x: 9.25, y: 10.2 })
  await page.evaluate(() => window.dispatchEvent(new PageTransitionEvent('pagehide')))
  await expect(page.getByTestId('survival-game')).toHaveAttribute('data-save-state', 'saved')
  await page.reload()
  await expect(page.getByTestId('camp-scene')).toHaveAttribute('data-ready', 'true')
  await expect.poll(() => position(page)).toEqual({ x: 9.25, y: 10.2 })
  await page.screenshot({ path: 'test-results/movement-precise-target.png' })
  expect(errors).toEqual([])
})

test('a new tap redirects immediately and diagonal interpolation changes both coordinates', async ({ page }) => {
  await enter(page)
  await page.clock.install()
  // Freeze between gestures so projection and tapping use the same moving camera frame.
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 50))
  await tapPoint(page, 9.3, 10.3)
  await page.clock.runFor(150)
  const before = await position(page)
  expect(before.x).toBeGreaterThan(7); expect(before.y).toBeGreaterThan(9)
  // Clear ground: the old (6.7, 11.2) point lies on the tree at (10, 14)'s canopy.
  await tapPoint(page, 6.7, 10.2)
  await page.clock.runFor(150)
  const after = await position(page)
  expect(after.x).toBeLessThan(before.x)
  expect(after.y).toBeGreaterThan(before.y)
  expect(Math.hypot(after.x - before.x, after.y - before.y)).toBeLessThan(.65)
  await page.screenshot({ path: 'test-results/movement-retarget.png' })
  await page.clock.runFor(1500)
  await expect.poll(() => position(page)).toEqual({ x: 6.7, y: 10.2 })
})

test('a saved move continues after reload without snapping to a cell or simulating background travel', async ({ page }) => {
  await enter(page)
  await page.clock.install()
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 50))
  await tapPoint(page, 9.2, 10.2)
  await page.clock.runFor(200)
  await page.evaluate(() => window.dispatchEvent(new PageTransitionEvent('pagehide')))
  await page.clock.runFor(50)
  const paused = await position(page)
  expect(Number.isInteger(paused.x)).toBe(false)
  await expect(page.getByTestId('survival-game')).toHaveAttribute('data-save-state', 'saved')
  await page.clock.runFor(5000)
  expect(await position(page)).toEqual(paused)
  await page.reload()
  await expect(page.getByTestId('camp-scene')).toHaveAttribute('data-ready', 'true')
  // Keep the clock frozen through reload, then render one paused frame at the restored position.
  await page.evaluate(() => window.dispatchEvent(new PageTransitionEvent('pagehide')))
  await page.clock.runFor(50)
  const restored = await position(page)
  expect(restored).toEqual(paused)
  await page.evaluate(() => window.dispatchEvent(new PageTransitionEvent('pageshow')))
  await page.clock.runFor(2000)
  await expect.poll(() => position(page)).toEqual({ x: 9.2, y: 10.2 })
})
